### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by Majow** [Noxalus/live-stream-chat-retriever#2]
after 'npm install' I did npm start and:

> D:\Live-Stream-Chat-Retriever-master>npm start
> 
> live-stream-chat-retriever@0.0.2 start D:\Live-Stream-Chat-Retriever-master
> node server.js
> 
> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'mkdirp'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (D:\Live-Stream-Chat-Retriever-master\server.js:7:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> npm ERR! node v4.4.3
> npm ERR! npm  v2.15.1
> npm ERR! code ELIFECYCLE
> npm ERR! live-stream-chat-retriever@0.0.2 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the live-stream-chat-retriever@0.0.2 start script 'node server.js'.
> npm ERR! This is most likely a problem with the live-stream-chat-retriever package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs live-stream-chat-retriever
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls live-stream-chat-retriever
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\Live-Stream-Chat-Retriever-master\npm-debug.log
> 
> D:\Live-Stream-Chat-Retriever-master>

debug log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'D:\Program Files\nodejs\node.exe',
> 1 verbose cli   'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'bugs',
> 1 verbose cli   'live-stream-chat-retriever' ]
> 2 info using npm@2.15.1
> 3 info using node@v4.4.3
> 4 silly mapToRegistry name live-stream-chat-retriever
> 5 silly mapToRegistry using default registry
> 6 silly mapToRegistry registry https://registry.npmjs.org/
> 7 silly mapToRegistry data Result {
> 7 silly mapToRegistry   raw: 'live-stream-chat-retriever',
> 7 silly mapToRegistry   scope: null,
> 7 silly mapToRegistry   name: 'live-stream-chat-retriever',
> 7 silly mapToRegistry   rawSpec: '',
> 7 silly mapToRegistry   spec: 'latest',
> 7 silly mapToRegistry   type: 'tag' }
> 8 silly mapToRegistry uri https://registry.npmjs.org/live-stream-chat-retriever
> 9 verbose request uri https://registry.npmjs.org/live-stream-chat-retriever/latest
> 10 verbose request no auth needed
> 11 info attempt registry request try #1 at 02:43:36
> 12 verbose request id 1c1f3bb9f2c57b47
> 13 http request GET https://registry.npmjs.org/live-stream-chat-retriever/latest
> 14 http 404 https://registry.npmjs.org/live-stream-chat-retriever/latest
> 15 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
> 15 verbose headers   'content-type': 'application/json',
> 15 verbose headers   'cache-control': 'max-age=0',
> 15 verbose headers   'content-length': '51',
> 15 verbose headers   'accept-ranges': 'bytes',
> 15 verbose headers   date: 'Sat, 30 Apr 2016 05:43:34 GMT',
> 15 verbose headers   via: '1.1 varnish',
> 15 verbose headers   age: '0',
> 15 verbose headers   connection: 'keep-alive',
> 15 verbose headers   'x-served-by': 'cache-iad2138-IAD',
> 15 verbose headers   'x-cache': 'MISS',
> 15 verbose headers   'x-cache-hits': '0',
> 15 verbose headers   'x-timer': 'S1461995014.105853,VS0,VE23' }
> 16 silly get cb [ 404,
> 16 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
> 16 silly get     'content-type': 'application/json',
> 16 silly get     'cache-control': 'max-age=0',
> 16 silly get     'content-length': '51',
> 16 silly get     'accept-ranges': 'bytes',
> 16 silly get     date: 'Sat, 30 Apr 2016 05:43:34 GMT',
> 16 silly get     via: '1.1 varnish',
> 16 silly get     age: '0',
> 16 silly get     connection: 'keep-alive',
> 16 silly get     'x-served-by': 'cache-iad2138-IAD',
> 16 silly get     'x-cache': 'MISS',
> 16 silly get     'x-cache-hits': '0',
> 16 silly get     'x-timer': 'S1461995014.105853,VS0,VE23' } ]
> 17 verbose stack Error: 404 Not Found: live-stream-chat-retriever
> 17 verbose stack     at makeError (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
> 17 verbose stack     at CachingRegistryClient.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:250:14)
> 17 verbose stack     at Request._callback (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
> 17 verbose stack     at Request.self.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:199:22)
> 17 verbose stack     at emitTwo (events.js:87:13)
> 17 verbose stack     at Request.emit (events.js:172:7)
> 17 verbose stack     at Request.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1036:10)
> 17 verbose stack     at emitOne (events.js:82:20)
> 17 verbose stack     at Request.emit (events.js:169:7)
> 17 verbose stack     at IncomingMessage.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:963:12)
> 18 verbose statusCode 404
> 19 verbose pkgid live-stream-chat-retriever
> 20 verbose cwd D:\Live-Stream-Chat-Retriever-master
> 21 error Windows_NT 10.0.10586
> 22 error argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "bugs" "live-stream-chat-retriever"
> 23 error node v4.4.3
> 24 error npm  v2.15.1
> 25 error code E404
> 26 error 404 Not Found: live-stream-chat-retriever
> 26 error 404
> 26 error 404 'live-stream-chat-retriever' is not in the npm registry.
> 26 error 404 You should bug the author to publish it (or use the name yourself!)
> 26 error 404
> 26 error 404 Note that you can also install from a
> 26 error 404 tarball, folder, http url, or git url.
> 27 verbose exit [ 1, true ]

I can't move from here XD

**Comment by Noxalus** [comment]
Hello,

You have old versions of Node JS and NPM (you use NPM v2.15.1 and Node JS v4.4.3). Can you try again with the recent ones? (I use NPM v3.7.3 and v5.9.0)

Can you provide the content of the files stored in the **logs** folder?

**Comment by mnowotny** [comment]
Hey, you can just run `npm install mkdirp` and start the script then.

**Comment by hayley** [comment]
I'm running an older version of node too because of something I have installed that isn't compatible with the latest version. I can confirm that what mnowotny suggested works on node v4.4.5 though.

Would it be possible to add `mkdirp` as a dependency to this project to prevent this issue in the future?

**Comment by Noxalus** [comment]
That's what I should have done from the beginning, thank you for having noticed me about this error.

I did the change in the last commit => https://github.com/Noxalus/Live-Stream-Chat-Retriever/commit/a95e398c9176bf2412b2153aa5182851e647b1b0
