### ISSUE TITLE
How do you change the font size?

### ISSUE THREAD

**Issue by beardedbob** [Noxalus/live-stream-chat-retriever#4]
Great little app that I use in OBS but how do I change the chat font size? THanks

**Comment by Noxalus** [comment]
You need to update [this file](https://github.com/Noxalus/Live-Stream-Chat-Retriever/blob/master/public/css/chat.css) and change the `font-weight` to something that matches your needs for the `.message` class ;)

**Comment by beardedbob** [comment]
I was maybe a bit early on the trigger. Swaping the weight from 700 to say 1400 doesn't change the size in obs. maybe this is because its only changing it in eh html window?

**Comment by Noxalus** [comment]
Hello, sorry for the delay. I was wrong (I didn't use CSS for a while 😅), the `font-weight` is used to put the text bolder or thinner. To change the text size, the property is `font-size`. Currently, the `font-size` of the `chat-line` class is set to `18px`, you can change this value easily from the CSS I linked above 😉
